config/routes.rb
Rails.application.routes.draw do
  resources :tweeps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweep.rb
class Tweep < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweeps_controller.rb
class TweepsController < ApplicationController
  require 'twitter'

  before_action :set_tweep, only: [:show, :edit, :update, :destroy]

  # GET /tweeps
  # GET /tweeps.json
        
  def get_tweet_sentiment tweet,ob
    
        # create TextBlob object of passed tweet text
        analysis = Sentimental.new
        analysis.load_defaults
        puts "iiiiiiiiiiiiiiiiiiiii"
        x=analysis.score tweet
        puts x
      if  x > 0.25
          ob['p']=ob['p']+1
      elsif x< -0.25
        ob['n']=ob['n']+1
      else
 
        ob['ne']=ob['ne']+1
      end 
        puts "ssentoiiiiii"
        return  analysis.sentiment tweet
            
     
     
end
     

  def index
   @ob={}
    @ob['p']=0
    @ob['n']=0
    @ob['ne']=0
    @tweeps = Tweep.all
    if @tweeps.last!=nil

        
    @client = Twitter::REST::Client.new do |config|
    config.consumer_key        = "cWyKKMvMaVOoXnHr3oYLIWYvv"
    config.consumer_secret     = "fjyWEqKy8wN91xJmfZgcibX6FHn7wxhEJ1STv0UatnLeaD9j9Q"
    config.access_token        = "956937190549811205-9baQu4duMt5EykFnHv9x1AeM3KOH1cA"
    config.access_token_secret = "yUmzSNKuQzS72U0e3E4VzNwWqXA1q6ieaSIsoxIiqoYzi"
  end
  @tweet=[]
  @client.search(@tweeps.last.query, result_type: "recent").take(10).collect do |tweet|
   t=tweet.text
    obj={}
    obj['text']=t
    obj['sentiment']=  get_tweet_sentiment t,@ob
    @tweet<<obj
    puts "ssssssssssssssssssss"
    puts @ob['p']
    puts @ob['n']
    puts @ob['ne']

  end 
end
  end

  # GET /tweeps/1
  # GET /tweeps/1.json
  def show

  end

  # GET /tweeps/new
  def new
    @tweep = Tweep.new
  end

  # GET /tweeps/1/edit
  def edit
  end

  # POST /tweeps
  # POST /tweeps.json
  def create
    @tweep = Tweep.new(tweep_params)

    respond_to do |format|
      if @tweep.save
        format.html { redirect_to tweeps_url, notice: "sentiment analysis of the keyword '#{@tweep.query}'" }
        format.json { render :show, status: :created, location: @tweep }
      else
        format.html { render :new }
        format.json { render json: @tweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeps/1
  # PATCH/PUT /tweeps/1.json
  def update
    respond_to do |format|
      if @tweep.update(tweep_params)
        format.html { redirect_to @tweep, notice: 'Tweep was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweep }
      else
        format.html { render :edit }
        format.json { render json: @tweep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeps/1
  # DELETE /tweeps/1.json
  def destroy
    @tweep.destroy
    respond_to do |format|
      format.html { redirect_to tweeps_url, notice: 'Tweep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweep
      @tweep = Tweep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweep_params
      params.require(:tweep).permit(:query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeps_helper.rb
module TweepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweetu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweeps/_form.html.erb
<%= form_for(tweep) do |f| %>
  <% if tweep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweep.errors.count, "error") %> prohibited this tweep from being saved:</h2>

      <ul>
      <% tweep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %>
    <%= f.text_field :query %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweeps/edit.html.erb
<h1>Editing Tweep</h1>

<%= render 'form', tweep: @tweep %>

<%= link_to 'Show', @tweep %> |
<%= link_to 'Back', tweeps_path %>

app/views/tweeps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweeps</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeps.each do |tweep| %>
      <tr>
        <td><%= tweep.query %></td>
        <td><%= link_to 'Show', tweep %></td>
        <td><%= link_to 'Edit', edit_tweep_path(tweep) %></td>
        <td><%= link_to 'Destroy', tweep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
tweet sentimental analysis
<br>
positivecount=  <%=@ob['p']%>  %
<br>
negativecount=  <%=@ob['n']%>  %
<br>
neutralcount=   <%=@ob['ne']%>  %

<br>
<%if @tweet!=nil%>
 <% @tweet.each do |tweet|%>
      <%=tweet['text']%>
      <br>
      sentiment::
      <%=tweet['sentiment']%>
      <br>
      <br>
      <%end%>
<br>
<%end%>


<br>

<%= link_to 'New Tweep', new_tweep_path %>

app/views/tweeps/new.html.erb
<h1>New Tweep</h1>

<%= render 'form', tweep: @tweep %>

<%= link_to 'Back', tweeps_path %>

app/views/tweeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Query:</strong>
  <%= @tweep.query %>
</p>

<%= link_to 'Edit', edit_tweep_path(@tweep) %> |
<%= link_to 'Back', tweeps_path %>